import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Script id="pre-hydration-dom-sanitize" strategy="beforeInteractive">
          {`
            (function () {
              try {
                // 브라우저 확장프로그램이 hydration 전에 DOM을 주입해 mismatch를 유발하는 경우가 있어 제거합니다.
                var el = document.getElementById('open-incognito-widget');
                if (el && el.parentNode) el.parentNode.removeChild(el);

                // 혹시 모를 변형 케이스(aria-label 기반)도 제거
                var nodes = document.querySelectorAll('[aria-label="현재 탭을 시크릿 모드에서 열기"]');
                for (var i = 0; i < nodes.length; i++) {
                  var n = nodes[i];
                  if (n && n.parentNode) n.parentNode.removeChild(n);
                }
              } catch (e) {}
            })();
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
